### PR TITLE
In progress: Initial draft of INDEX token KPIs for Issue #67 (TWG - Low Priority - Low Effort - INDEX token KPIs)

### PR DESCRIPTION
**Pull request by ericlinML**
For Issue #67 (TWG - Low Priority - Low Effort - INDEX token KPIs), I've started working on this and have finished subtasks e-j

Since it's my first time contributing (still very excited to be a part of this), please let me know if I've done anything wrong or can fix my procedure / code to any standards. 

https://github.com/SetProtocol/index-coop-analytics/issues/67#issuecomment-895696210

### CODE REVIEW

**Comment by ericlinML** [comment]
Short of refining the presentation into something like a slide deck, I think this is about the limit of presenting from a Jupyter notebook (files named 'showcase...' under kpis/index-token-kpis/). If you guys are okay with it, I think the PR is ready. I've also included a conda yaml virtual environment file so someone can install my environment and easily rerun the notebook (indexTokenKPIs.ipynb) to get updated stats.

**Comment by josephd8** [comment]
@ericlinML one small edit that would be awesome - could you change the folder name to `index-token-kpis` instead of just `index-token-kpi` - sorry, I know it is small but I try to keep the folder structures uniform.

Then I am going to leave this issue and the PR `in review` for just a bit to give Matt and others a chance to respond and ask any follow ups. Thanks for your work here!

**Comment by ericlinML** [comment]
@josephd8 Not a problem with the folder naming, and it makes sense to get some eyes on it!

**Comment by ericlinML** [comment]
I waited to rename the folder (just renamed it now) and haven't heard from Matt Graham. Obviously no rush for this thing, but should I ping him?

**Comment by josephd8** [comment]
@ericlinML - can we actually put these all in a sub-folder, so the structure would be `index-token-kpis/[folder]/*`

If you can make that update when you get a chance, then I will merge this. Sorry for the double take on the folder structure.

**Comment by ericlinML** [comment]
not a problem, i named it "index-eth-tokens-analysis" but let me know if you would prefer a different name!

**Pull request merged**
