### PR TITLE
Growth KPIs Dashboard

### PR DESCRIPTION
**Pull request by ehrena**
Starting a repo to work on Issue #29  -- adding period growth metrics to core dashboard assets to streamline analysis and decision making. Adding @jackiep00 and @josephd8 for visibility.

https://github.com/SetProtocol/index-coop-analytics/issues/29

### CODE REVIEW

**Comment by ehrena** [comment]
@josephd8 added the SQLs that power the line charts. I left the tables out for now because it is pretty redundant... all I do to get those is keep the raw numbers in the final query sort by date in descending order, and limit rows by 7

**Comment by josephd8** [comment]
Awesome @ehrena ! So I think the last things to add would be:

- BED Unit Supply
- the last four tables for those product unit supply views

And then we can close out this issue and merge this PR. We will have to do some updating on some these once we get a re-vamp of all our exposure queries over the next week or two, but that will be a separate issue and task.

**Comment by ehrena** [comment]
@josephd8 will make these additions ASAP

**Comment by ehrena** [comment]
@josephd8 made the remaining changes -- added BED and the summary tables

**Comment by josephd8** [comment]
Awesome! I am going to merge this PR and close the issue. We will likely build on this in the future! You should change the dashboard name to Index Coop Growth Metrics or something like that so it is recognizable! @ehrena

**Pull request merged**
