### PR TITLE
draft of eth2x-fli balances and ratio on hourly basis

### PR DESCRIPTION
**Pull request by jorijnsmit**
This is tackling two tickets:
- cETH / USDC debt / COMP Balance
- Leverage Ratio over time

Only thing left to do is to find a way to properly convert USDC debt to hourly. WIP.

### CODE REVIEW

**Comment by josephd8** [comment]
@jorijnsmit awesome to see this PR come in - I am only seeing 1 file for the balances, and nothing for the leverage ratio? Am I missing something?

**Comment by jorijnsmit** [comment]
@josephd8 no the ratio just wasn't calculated yet in the last query. Added now but with some caveats, so still WIP. See TODO notes in the query.

Some of those todos can be fixed by switching to a daily resolution instead of hourly. Not sure of the specs though, is daily fine @josephd8?

Query result and chart here: https://duneanalytics.com/queries/51832

**Comment by josephd8** [comment]
@jorijnsmit I think we need to get to hourly if possible to allow the type of monitoring the FLI team is looking for - I would suggest shooting this dune query/visual over to the FLI team for their feedback right now, even if it is still a WIP. Looks like it is coming together!

**Comment by josephd8** [comment]
@jorijnsmit are you good for me to merge this?

**Comment by josephd8** [comment]
I will move the issue to "in review" on the board and wait til the team reviews. If all is good from them then I will merge. Thanks!

**Pull request merged**
