### PR TITLE
Draft of dpi nav vs dpi market price query.

### PR DESCRIPTION
**Pull request by Lorengo**

### CODE REVIEW

**Comment by josephd8** [comment]
@Lorengo this is looking awesome! Great work. So a couple things:

1) I would love to have I think three different views of this:

* all-time hourly
* past 30-days hourly
* past 3 days by minute

However, I think we will need to do the CREAM pricing differently in order to get it to the minute - either we try to build a price feed that is closer to per-minute using uniswap, or we just use hourly prices for CREAM and acknowledge that is a bit of a gap.

2) I just reached out to Dylan (tagged you in discord) to see if we can get the actual weights / nominal amount from all rebalances so that we can cross-check the nominal amounts we are calculating against those. That would be the one area I want to make sure we are super accurate if possible.

Let me know if those make sense or you have any questions.

**Comment by Lorengo** [comment]
Hello, @josephd8,I have finished the code of DPI nav vs market price queries which include:

- all-time hourly
- past 30-days hourly
- past 3 days by minute

The dashboard is here :https://duneanalytics.com/loren/Index-Coop-products-nav-vs-market-price

Next, we need the  actual nominal amounts data to cross validate the queries.

**Comment by josephd8** [comment]
@Lorengo just reviewed your queries, this is really awesome work! I am pretty confident in the efficacy here, but I think it is a good idea to check against the nominal amounts recorded in the CMS. I will keep pushing to get that data so we can close this out.

**Comment by Lorengo** [comment]
Hello, @josephd8,I have finished the draft of mvi nav vs its market price queries which include:

- all-time by hour
- past 30-days by hour
- past 3 days by minute

The dashboard is here :https://duneanalytics.com/loren/Index-Coop-products-nav-vs-market-price

**Pull request merged**
