### PR TITLE
DPI Liquidity Mining Analysis

### PR DESCRIPTION
**Pull request by ripples3**

### CODE REVIEW

**Comment by josephd8** [comment]
@ripples3 @jackiep00 can we get the DPI and MVI queries in the same folder and make sure the folder is named appropriately, then we can merge this

**Comment by jackiep00** [comment]
This is a WIP PR, there’s a few irregularities we’re checking on. Will let
you know when it’s all ready to go

**Comment by josephd8** [comment]
Perfect, thanks!

**Comment by jackiep00** [comment]
Alright @josephd8, it's ready to go! dashboard is here.

https://dune.xyz/emesrever/Index-Coop-MVI-LP-Staker-Analysis

Lets close this out - any other changes are likely to be cosmetic. we'll merge them in another time.

**Comment by ripples3** [comment]
Closing this now

**Comment by ripples3** [comment]
Reopening it as PR has not been merge yet.

**Pull request merged**
